
#define MEASURE_STATE_VALUES_DEBUG_LOGS
#define GET_STATE_LAYER_INFO_DEBUG_LOGS
// #define MEASURE_DEBUG_LOGS
// #define INSTRUCTIONS_HANDLER_LOGS
// #define RECEIVED_OPERATION_LOGS
// #define TOFFOLI_DEBUG_LOGS
// #define CONTROLLEDZ_DEBUG_LOGS
// #define CONTROLLEDX_DEBUG_LOGS
// #define HADAMARD_DEBUG_LOGS
// #define PAULIZ_DEBUG_LOGS
// #define PAULIY_DEBUG_LOGS
// #define PAULIX_DEBUG_LOGS
#define HANDLER_STATES_DEBUG

#define OUTPUT_LOGS                                                                 \
	TOFFOLI_DEBUG_LOGS || CONTROLLEDZ_DEBUG_LOGS || CONTROLLEDX_DEBUG_LOGS ||       \
		HADAMARD_DEBUG_LOGS || PAULIZ_DEBUG_LOGS || PAULIY_DEBUG_LOGS ||            \
		PAULIX_DEBUG_LOGS || HANDLER_STATES_DEBUG || RECEIVED_OPERATION_LOGS ||     \
		INSTRUCTIONS_HANDLER_LOGS || MEASURE_DEBUG_LOGS ||                          \
		GET_STATE_LAYER_INFO_DEBUG_LOGS || MEASURE_STATE_VALUES_DEBUG_LOGS
