name: C++ build with Make

on:
  push:
    branches: [ "master", "integrated-testing" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: setup
      run: sudo apt-get install -y libopenmpi-dev && sudo apt-get install -y make

    - name: configure
      run: chmod +x configure && ./configure

    - name: make
      run: make -j5

  testing:

    runs-on: self-hosted

    steps:
    - name: 3-qubit testing
      run: python3 scripts/test.py openqasmTests/q3_grovers.openqasm 3 "100 100 0"
        && python3 scripts/test.py openqasmTests/q3_test1.openqasm 3 "100 50 100"

  
